[mypy]
ignore_missing_imports = True
disallow_untyped_defs = False
check_untyped_defs = False
show_error_codes = True
disable_error_code = assignment, var-annotated, override, index, operator, attr-defined, misc, name-defined
